#include "pins.h"
#include "digio.h"
//#include <avr/io.h>
#include <stm32f0xx.h>
#include "stm32f0xx_nucleo.h"

const Pin pins[] =
  {
		  //i pin digitali sono:
		  //PA5,PA6,PA7,PA8,PA9,PA10;
		  //(PA2,PA3 dedicati uart)
		  //PB3,PB4,PB5,PB6,PB8,PB9,PB10;
		  //PC7.
    //0
    {
      //PA5
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=5,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //1
    {
       //PA6
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=6,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //2
    {
      //PA7
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=7,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //3
    {
      //PA8
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=8,
	  .ccm1_register=0,
	  .dutyc_register=0,
	  .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //4
    {
      //PA9
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=9,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //5
    {
      //PA10
      .in_register=&GPIOA->IDR,
      .out_register=&GPIOA->ODR,
      .dir_register=&GPIOA->MODER,
      .bit=10,
	  .ccm1_register=0,
	  .dutyc_register=0,
	  .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //6
    {
      //PB3
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=3,
	  .ccm1_register=&TIM2->CCMR1,
	  .dutyc_register=&TIM2->CCR1,
	  .com_mask=TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1FE,
	  .afr_register[0]=&GPIOB->AFR[0],
	  .afr_register[1]=&GPIOB->AFR[1]
    },
    //7
    {
      //PB4
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=4,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //8
    {
      //PB5
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=5,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //9
    {
      //PB6
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=6,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //10
    {
      //PB8
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=8,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //11
    {
      //PB9
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=9,
	  .ccm1_register=0,
	  .dutyc_register=0,
	  .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    },
    //12
    {
      //PB10
      .in_register=&GPIOB->IDR,
      .out_register=&GPIOB->ODR,
      .dir_register=&GPIOB->MODER,
      .bit=10,
	  .ccm1_register=&TIM2->CCMR1,
	  .dutyc_register=&TIM2->CCR1,
	  .com_mask=TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1FE,
	  .afr_register[0]=&GPIOB->AFR[0],
	  .afr_register[1]=&GPIOB->AFR[1]
    },
    //13
    {
      //PC7
      .in_register=&GPIOC->IDR,
      .out_register=&GPIOC->ODR,
      .dir_register=&GPIOC->MODER,
      .bit=7,
	  .ccm1_register=0,
	  .dutyc_register=0,
      .com_mask=0,
	  .afr_register[0]=0,
	  .afr_register[1]=0
    }
  };
